### ISSUE TITLE
Binary operator ambiguity

### ISSUE THREAD

**Issue by rcdailey** [aantron/better-enums#23] opened 2016-07-06 21:25 UTC
Consider this example:

```
BETTER_ENUM(TestEnum, int, One, Two);

int main()
{
    TestEnum mine = TestEnum::One;

    if (mine == TestEnum::One)
    {
    }
}
```

The comparison using `==` above fails on MSVC and GCC with the following:

```
main.cpp:1193:14: error: ambiguous overload for 'operator==' (operand types are 'TestEnum' and 'TestEnum::_enumerated')
     if (mine == TestEnum::One)
         ~~~~~^~~~~~~~~~~
main.cpp:1193:14: note: candidate: operator==(TestEnum::_enumerated, TestEnum::_enumerated) <built-in>
main.cpp:1193:14: note: candidate: operator==(int, int) <built-in>
```

Since you're using an unscoped enumeration internally, a direct comparison cannot be performed because the compiler can cast `_enumerated` either to `int` or `TestEnum`.

Yes, I realize I can use the `+` operator but I find this to be unintuitive semantically and unnecessary.

As a test I added an additional operator overload:

```
BETTER_ENUMS_CONSTEXPR_ inline bool operator ==(const Enum &a, const Enum::_enumerated &b)  \
    { return a._to_integral() == b; }                           \
```

This fixed the compiler error. I feel that the Enum class should explicitly handle operations on its enumerated type. I also find it odd that there is no way to grab the internal enumerated type that a Enum variable represents, much like `Enum::_to_integer()` but instead something like `Enum::_to_enum()`, which has a return type of `Enum::_enumerated`.

Thoughts? I'm happy to contribute a PR for this if you feel that this is a good addition.

**Comment by aantron** [comment] 2016-07-07 21:08
Hi,

`operator +` and the comparison operators are an ugly area of Better Enums indeed, and I agree that it would be nice to improve it. However, just adding the comparison operator you suggest to current Better Enums makes other comparisons (e.g. `make -C test` to see output) ambiguous. Given the constraints I had previously, I decided that those comparisons were more important to get right. However, the constraints have since changed.

If you can find a way to avoid ambiguities better, especially if you also avoid `operator +`, a PR is very welcome. If you can do it, but only using `BETTER_ENUMS_STRICT_CONVERSION`, that's fine too – that is probably how Better Enums will always work in the future. It probably won't have any implicit conversions to an unscoped enum type.

---

You can currently convert to the internal enum type using `(Enum::_enumerated)your_enum`, but IIRC that only works without `BETTER_ENUM_STRICT_CONVERSION`, and, either way, it's ugly, redundant, and fragile. An actual `_to_enum` function is probably a good idea for a separate PR, but I am not sure what it should do in the case of strict conversions – evaluate to the strong enum type (probably), or the internal enum type used just to get `Foo::Bar` syntax (unlikely). In the former case, it should be as easy to implement as wrapping the existing `operator SwitchType`.

---

Thanks!

**Comment by rcdailey** [comment] 2016-07-08 12:50
I'm not in a position where I can run your unit tests at the moment, nor do I have make on this system (Windows OS). I am also not interested in using posix emulation. Not sure if you have CMake scripts but that would make building your project a breeze on multiple platforms. Beside the point though.

Could you give me an example of which ambiguities it introduces, according to your test output? I was thinking that scoped enumerations would be the best solution to this problem. You currently store the enumerator value as a bare type, instead of via the type of the enumeration itself. I think that if you went the scoped enum route, you would be best to store it as the type of the num, and perform a `static_cast` in functions where you need to do some sort of marshalling. In all other cases, keeping the value as original and type safe as possible would be a fundamental goal. But then again, this is easier said than done I'm sure given the complexity of what you are trying to solve.

I'll toy around with this some and let you know what I come up with.

**Comment by aantron** [comment] 2016-07-08 18:42
> Could you give me an example of which ambiguities it introduces, according to your test output?

Hmm, it's failing on comparisons with values of types that convert to Better Enums:

```cpp
(+Compression::None == default_)
```

I defined such types in this [example](http://aantron.github.io/better-enums/demo/SpecialValues.html#MakingTheSyntaxNicer). However, I don't think this is a serious problem – not even sure anyone has types like this. So we can just remove the example, or there may be an easy workaround.

This wasn't what originally caused me to avoid the extra comparison operators you are trying to add, but I can't remember or figure out now what it was. So, as long as you do some thorough tests (make sure mixed comparisons on both sides are unambiguous, etc.), it should be fine to add them.

The rest of the tests are passing.

I vaguely remember there being some weird corner case, that caused me to decide to just uniformly require `operator +`, instead of letting users think the problem is solved until Better Enums suddenly breaks after some trivial code edit. IIRC this corner case would not occur if we converted to scoped enums. Sorry that I can't be more specific :/ I thought the tests covered it, but I guess they don't, or it was accidentally fixed at some point.

---

> I was thinking that scoped enumerations would be the best solution to this problem.

Most likely. Better Enums is definitely going that route. @cheparukhin recently expressed an interest in this as well (as have others in the past) – perhaps you should coordinate dropping unscoped enum support together. Otherwise, I will do it "later" (unfortunately).

Some background:

I chose to declare an internal unscoped enum *type* so that you could access the enumerands using `Foo::A` syntax, where `Foo` is a Better Enum. A scoped internal *type* would, I think, introduce an extra name in the middle. However, this unscoped enum type doesn't have to be the type `Foo` converts to, or the type of its internal value. It does seem like you would have to have an implicit conversion *from* the type to a Better Enum, though, so you could use `Foo::A` as if it was a Better Enum.

If you don't have Better Enums converting back to that unscoped type, but to an external scoped type instead, it [complicates](http://aantron.github.io/better-enums/OptInFeatures.html#StrictConversions) the `switch` syntax. This is because `switch` will be done at the scoped type, while the constants in the cases will be of the unscoped type, and the compiler will not do two implicit conversions to go from the latter to the former. `operator +` is one way to solve that, but there are other approaches.

---

> I'm not in a position where I can run your unit tests at the moment, nor do I have make on this system (Windows OS). I am also not interested in using posix emulation. Not sure if you have CMake scripts but that would make building your project a breeze on multiple platforms.

Better Enums actually is [using CMake](https://github.com/aantron/better-enums/blob/18cbeb0808697a9a71ce281c033ae468d74e2e29/test/CMakeLists.txt) exactly for that reason. The `Makefile` drives that. POSIX emulation is not really needed for Better Enums testing, it's just an easy way to get Make, and Python for CxxTest, and use some common tools on multiple platforms. The tests should work with the Win32 ports of those tools. But I see your point. I've opened #24 for making development easier on Windows, without having to resort to Cygwin.

**Comment by rcdailey** [comment] 2016-07-08 20:05
Well I thought the reason you didn't support scoped enums is due to C++03/98 support. You'd be forgoing support of those standards by doing this. Which I don't think is a bad thing,  C++11 is already almost 6 years old.

**Comment by rcdailey** [comment] 2016-07-08 20:20
Also you could do some trickery like this:

```
template<typename T>
class strong_enumerator
{
public:
    using value_type = T;

private:
    T value_;
};

// ...........

class MyFooEnum
{
public:
    // Generated by preprocessor; expanded for example purposes
    strong_enumerator<int> MY_FIRST_ENUM;
    strong_enumerator<int> MY_SECOND_ENUM;

private:
    strong_enumerator<int> value_;
};
```

And usage:

```
BETTER_ENUM(MyFooEnum, int, MY_FIRST_ENUM, MY_SECOND_ENUM);

// ...........

MyFooEnum f = MyFooEnum::MY_FIRST_ENUM;
```

This makes enumerators strongly typed without breaking backward compatibility to C++03. It also solves the quirkiness that mandated the unary `+` operator (most likely, I didn't dig too much into it).

This is me just throwing some food for thought in a text box. I haven't actually coded anything in a practical test. But if I were to sit down for a few hours (which I will do later) and try to rethink this from the ground up, this is probably the direction I would go. You can do a lot of cool stuff with enumerators when they are represented by an actual class, which can have its own operators and functionality built into it.

**Comment by aantron** [comment] 2016-07-08 21:40
Heya, I will respond in the new issue (#25), so that anyone interested can read it without having to see the other points in this issue first. You are welcome to repost your comments there as well.

**Comment by aantron** [comment] 2019-08-17 19:29
Closing in favor of #25.

**Closed by aantron** 2019-08-17 19:29 UTC
